baseurl = "/"
languageCode = "sv-se"
title = "Alviks M책leri"

[menu]
  [[menu.main]]
    identifier = "nyheter"
    name = "Nyheter"
    title = "Nyheter sectiion"
    url = "/nyheter/"
    weight = 4
  [[menu.main]]
    identifier = "karriar"
    name = "Jobba hos oss"
    title = "Karri채r sectiion"
    url = "/karriar/"
    weight = 3
  [[menu.main]]
    identifier = "kontakt"
    name = "Kontakt"
    title = "Kontakt sectiion"
    url = "/kontakt/"
    weight = 6
  [[menu.main]]
    identifier = "tjanster"
    name = "Tj채nster"
    title = "Tj채nster sectiion"
    url = "/tjanster/"
    weight = 1
  [[menu.main]]
    identifier = "referenser"
    name = "Referenser"
    title = "Referenser sectiion"
    url = "/referenser/"
    weight = 2
  [[menu.main]]
    identifier = "om-oss"
    name = "Om oss"
    title = "Om oss sectiion"
    url = "/om-oss/"
    weight = 5
